#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2024 Celeste Sinéad

# This file is part of Friture.
#
# Friture is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# Friture is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Friture.  If not, see <http://www.gnu.org/licenses/>.

# Pitch estimator adapted from libf0 (MIT License):
# https://github.com/groupmm/libf0
# Based on SWIPE algorithm by Arturo Camacho:
# Arturo Camacho, John G. Harris; A sawtooth waveform inspired pitch estimator for speech and music. J. Acoust. Soc. Am. 1 September 2008; 124 (3): 1638–1652. https://doi.org/10.1121/1.2951592
# Released under GPLv3 for inclusion in Friture.

from collections.abc import Generator
import logging
import math as m
import numpy as np

from PyQt5 import QtWidgets
from PyQt5.QtCore import pyqtSignal, pyqtProperty # type: ignore
from PyQt5.QtCore import QObject, QSettings, Qt
from PyQt5.QtQuick import QQuickWindow
from PyQt5.QtQuickWidgets import QQuickWidget
from PyQt5.QtQml import QQmlComponent, QQmlEngine
from typing import Any, Optional

from friture.audiobackend import SAMPLING_RATE
from friture.audiobuffer import AudioBuffer
from friture.audioproc import audioproc
from friture.curve import Curve
from friture.pitch_tracker_settings import (
    DEFAULT_MIN_FREQ,
    DEFAULT_MAX_FREQ,
    DEFAULT_DURATION,
    DEFAULT_FFT_SIZE,
    DEFAULT_MIN_DB,
    DEFAULT_C_RES,
    DEFAULT_P_CONF,
    PitchTrackerSettingsDialog,
)
from friture.plotting.coordinateTransform import CoordinateTransform
import friture.plotting.frequency_scales as fscales
from friture.ringbuffer import RingBuffer
from friture.scope_data import Scope_Data
from friture.store import GetStore
from friture.qml_tools import qml_url, raise_if_error


def frequency_to_note(freq: float) -> str:
    if np.isnan(freq) or freq <= 0:
        return ""
    # number of semitones from C4
    # A4 = 440Hz and is 9 semitones above C4
    semitone = round(np.log2(freq/440) * 12) + 9
    octave = int(np.floor(semitone / 12)) + 4
    notes = ["C", "C♯", "D", "D♯", "E", "F", "F♯", "G", "G♯", "A", "A♯", "B"]
    return f'{notes[semitone % 12]}{octave}'

def format_frequency(freq: float) -> str:
    if freq < 1000:
        return f'{freq:.0f} Hz ({frequency_to_note(freq)})'
    else:
        return f'{freq/1000:.1f} kHz ({frequency_to_note(freq)})'

def fastParabolicInterp(y1, y2, y3):
    """
    Estimates, via parabolic interpolation, the local extremum (vertex)
    from three evenly spaced samples.

    SWIPE generates a discretized pitch strength "curve" for its pitch
    candidates (bins) by calculating the inner product with kernels made
    of cosine lobes, which allows the underlying, smooth function to be
    modeled using a Taylor series with even powers. Higher order terms
    don't contribute significantly, so a simple parabolic interpolation
    can generate sub-bin pitch accuracy.

    Args:
        y1 (float): The pitch strength at frequency bin i - 1.
        y2 (float): The pitch strength at frequency bin i.
        y3 (float): The pitch strength at frequency bin i + 1.

    Returns:
        tuple:
            vx (float): The position offset (in index) of the interpolated
                peak relative to the center index.
            vy (float): The interpolated pitch strength value at the peak.
    """
    a = (y1 - 2*y2 + y3) / 2
    b = (y3 - y1) / 2
    #c = y2

    vx = -b / (2 * a + np.finfo(np.float64).eps) # Avoids division by zero
    vy = a * vx**2 + b * vx + y2

    return vx, vy

def calcKernel(f, freqList):
    """
    Generates a SWIPE-ish frequency-domain kernel centered on a candidate
    fundamental frequency 'f'.

    SWIPE kernels are normalized, continuous curves generated by sums of
    positive and negative cosine lobes: positive lobes at the selected
    harmonics and negative lobes between. This SWIPE implementation uses a
    mixture of harmonics from SWIPE and SWIPE', tailored for a better match
    to human voices. The magnitude of the kernels decays as the square root
    of frequency, except for the fundamental and first harmonic, which are
    given equal weighting.

    Args:
        f (float): Fundamental frequency (in Hz).
        freqList (ndarray): Array of frequency bins for the kernel (in Hz).

    Returns:
        ndarray: Normalized kernel corresponding to the fundamental 'f'.
    """

    # Harmonics are a mix of SWIPE and SWIPE'. Good match for human voice.
    harmonics = np.array([1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 13, 17, 19, 23])

    # Kernels don't need harmonics beyond the Nyquist frequency.
    maxPossibleHarmonics = int(freqList[-1] / f)
    maxPossibleHarmonics = min(maxPossibleHarmonics, len(harmonics))
    selectedHarmonics = harmonics[:maxPossibleHarmonics]

    # Initialize the kernel
    k = np.zeros_like(freqList)

    # Normalize frequencies around the current frequency, f. Useful for harmonic comparisons.
    ratio = freqList / f

    for h in selectedHarmonics:
        a = np.abs(ratio - h)  # Calculate distance from harmonic

        # Create boolean masks for peak and valley bins based on the distance from the harmonic
        peakBins = a < 0.25
        valleyBins = np.logical_and(0.25 < a, a < 0.75)

        # Generate the cosine lobes for the peaks and valleys of the kernel
        k[peakBins] = np.cos(ratio[peakBins] * 2 * np.pi)
        k[valleyBins] += np.cos(ratio[valleyBins] * 2 * np.pi) / 2

    # Apply decay only after the first harmonic by using a mask
    # Often the first harmonic for male voices has a higher amplitude than the fundamental frequency
    decay = np.ones_like(freqList)
    mask = freqList > 2 * f
    decay[~mask] = np.sqrt(1.0 / (2*f))
    decay[mask] = np.sqrt(1.0 / freqList[mask])

    k *= decay

    # K+-normalize kernel
    k /= np.linalg.norm(k[k > 0])

    return k


class PitchTrackerWidget(QtWidgets.QWidget):
    def __init__(self, parent: QtWidgets.QWidget, engine: QQmlEngine):
        super().__init__(parent)

        self.logger = logging.getLogger(__name__)

        self.setObjectName("PitchTracker_Widget")

        store = GetStore()
        self._pitch_tracker_data = Scope_Data(store)
        store._dock_states.append(self._pitch_tracker_data)
        state_id = len(store._dock_states) - 1

        self._curve = Curve()
        self._curve.name = "Ch1" # type: ignore [assignment]
        self._pitch_tracker_data.add_plot_item(self._curve)

        # cast for qt properties which aren't properly typed
        tracker_data: Any = self._pitch_tracker_data
        tracker_data.vertical_axis.name = "Frequency (Hz)"
        tracker_data.vertical_axis.setTrackerFormatter(
            format_frequency)
        tracker_data.vertical_axis.show_minor_grid_lines = True
        tracker_data.horizontal_axis.name = "Time (sec)"
        tracker_data.horizontal_axis.setTrackerFormatter(
            lambda x: "%#.3g sec" % (x))

        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setContentsMargins(2, 2, 2, 2)

        self.quickWidget = QQuickWidget(engine, self)
        self.quickWidget.statusChanged.connect(self.on_status_changed)
        self.quickWidget.setResizeMode(QQuickWidget.SizeRootObjectToView)
        self.quickWidget.setSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.quickWidget.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.quickWidget.setSource(qml_url("Scope.qml"))

        raise_if_error(self.quickWidget)

        root: Any = self.quickWidget.rootObject()
        root.setProperty("stateId", state_id)

        self.gridLayout.addWidget(self.quickWidget, 0, 0, 1, 1)

        self.pitch_view_model = PitchViewModel(self)
        pitch_window = QQuickWindow()
        pitch_component = QQmlComponent(engine, qml_url("PitchView.qml"), self)
        raise_if_error(pitch_component)
        pitch_object: Any = pitch_component.createWithInitialProperties(
            {
                "parent": pitch_window.contentItem(),
                "pitch_view_model": self.pitch_view_model
            },
            engine.rootContext()
        )
        pitch_object.setParent(pitch_window)
        pitch_widget = QtWidgets.QWidget.createWindowContainer(pitch_window, self)
        pitch_widget.setSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        pitch_widget.setFixedWidth(int(pitch_object.width()))
        self.gridLayout.addWidget(pitch_widget, 0, 1)

        self.min_freq = DEFAULT_MIN_FREQ
        self.max_freq = DEFAULT_MAX_FREQ
        self._pitch_tracker_data.vertical_axis.setRange( # type: ignore
            self.min_freq, self.max_freq)
        self._pitch_tracker_data.vertical_axis.setScale( # type: ignore
            fscales.OctaveC)
        self.vertical_transform = CoordinateTransform(
            self.min_freq, self.max_freq, 1, 0, 0)
        self.vertical_transform.setScale(fscales.OctaveC)

        self.duration = DEFAULT_DURATION
        self._pitch_tracker_data.horizontal_axis.setRange( # type: ignore
            -self.duration, 0.)

        self.settings_dialog = PitchTrackerSettingsDialog(self)

        self.audiobuffer: Optional[AudioBuffer] = None
        self.tracker = PitchTracker(RingBuffer())
        self.update_curve()


    # method
    def set_buffer(self, buffer: AudioBuffer) -> None:
        self.audiobuffer = buffer
        self.tracker.set_input_buffer(buffer.ringbuffer)

    def handle_new_data(self, floatdata: np.ndarray) -> None:
        if self.tracker.update():
            self.update_curve()
            self.pitch_view_model.pitch = self.tracker.get_latest_estimate() # type: ignore

    def update_curve(self) -> None:
        pitches = self.tracker.get_estimates(self.duration)
        pitches = 1.0 - self.vertical_transform.toScreen(pitches) # type: ignore
        pitches = np.clip(pitches, 0, 1)
        times = np.linspace(0, 1.0, pitches.shape[0])
        self._curve.setData(times, pitches)

    def on_status_changed(self, status: QQuickWidget.Status) -> None:
        if status == QQuickWidget.Error:
            for error in self.quickWidget.errors():
                self.logger.error("QML error: " + error.toString())

    # method
    def canvasUpdate(self) -> None:
        # nothing to do here
        return

    def set_min_freq(self, value: int) -> None:
        self.min_freq = value
        self._pitch_tracker_data.vertical_axis.setRange(self.min_freq, self.max_freq) # type: ignore
        self.vertical_transform.setRange(self.min_freq, self.max_freq)

    def set_max_freq(self, value: int) -> None:
        self.max_freq = value
        self._pitch_tracker_data.vertical_axis.setRange(self.min_freq, self.max_freq) # type: ignore
        self.vertical_transform.setRange(self.min_freq, self.max_freq)

    def set_duration(self, value: int) -> None:
        self.duration = value
        self._pitch_tracker_data.horizontal_axis.setRange(-self.duration, 0.) # type: ignore

    def set_min_db(self, value: float) -> None:
        self.tracker.min_db = value

    def set_conf(self, value: float) -> None:
        self.tracker.conf = value
        self.conf = value

    # slot
    def settings_called(self, checked: bool) -> None:
        self.settings_dialog.show()

    # method
    def saveState(self, settings: QSettings) -> None:
        self.settings_dialog.save_state(settings)

    # method
    def restoreState(self, settings: QSettings) -> None:
        self.settings_dialog.restore_state(settings)


class PitchViewModel(QObject):
    pitch_changed = pyqtSignal(float)

    def __init__(self, parent: QObject):
        super().__init__(parent)
        self._pitch = 0.0

    @pyqtProperty(str, notify=pitch_changed)
    def pitch(self) -> str:
        if not self._pitch or np.isnan(self._pitch):
            return '--'
        elif self._pitch < 1000:
            return f"{self._pitch:.0f}"
        else:
            return f"{self._pitch/1000:.2f}"

    @pitch.setter # type: ignore
    def pitch(self, pitch: float):
        self._pitch = pitch
        self.pitch_changed.emit(pitch)

    @pyqtProperty(str, notify=pitch_changed) # type: ignore
    def pitch_unit(self) -> str:
        if self._pitch >= 1000.0:
            return "kHz"
        else:
            return "Hz"

    @pyqtProperty(str, notify=pitch_changed) # type: ignore
    def note(self) -> str:
        if not self._pitch or np.isnan(self._pitch):
            return '--'
        else:
            return frequency_to_note(self._pitch)


class PitchTracker:
    def __init__(
        self,
        input_buf: RingBuffer,
        fft_size: int = DEFAULT_FFT_SIZE,
        overlap: float = 0.75,
        sample_rate: int = SAMPLING_RATE,
        min_db: float = DEFAULT_MIN_DB,
        min_freq: float = DEFAULT_MIN_FREQ,  # Add min_freq
        max_freq: float = DEFAULT_MAX_FREQ,  # Add max_freq
        cres: int = DEFAULT_C_RES,
        conf: float = DEFAULT_P_CONF

    ):
        self.fft_size = fft_size
        self.overlap = overlap
        self.sample_rate = sample_rate
        self.min_db = min_db
        self.min_freq = min_freq  # Save min_freq
        self.max_freq = max_freq  # Save max_freq
        self.cres = cres # Resolution of pitcher tracker in cents
        self.conf = conf # Confidence cutoff

        self.input_buf = input_buf
        self.input_buf.grow_if_needed(fft_size)
        self.next_in_offset = self.input_buf.offset

        self.out_buf = RingBuffer()
        self.out_offset = self.out_buf.offset

        self.proc = audioproc()
        self.proc.set_fftsize(self.fft_size)

        # Only generate the log-spaced pitch candidates and kernels for the SWIPE algorithm on instantiation.
        self._init_swipe()

    def set_input_buffer(self, new_buf: RingBuffer) -> None:
        self.input_buf = new_buf
        self.input_buf.grow_if_needed(self.fft_size)
        self.next_in_offset = self.input_buf.offset

    def update(self) -> bool:
        new = [self.estimate_pitch(f) for f in self.new_frames()]
        self.out_buf.push(np.array([new]), 0)
        self.out_offset = self.out_buf.offset
        return len(new) != 0

    def get_estimates(self, time_s: float) -> np.ndarray:
        step_size = m.floor(self.fft_size * (1.0 - self.overlap))
        num_results = m.floor(time_s / (step_size / self.sample_rate)) + 1
        return self.out_buf.data_indexed(self.out_offset, num_results)[0,:]

    def get_latest_estimate(self) -> float:
        return self.out_buf.data_indexed(self.out_offset, 1)[0,0]

    def new_frames(self) -> Generator[np.ndarray, None, None]:
        assert self.input_buf.offset >= self.next_in_offset
        while self.next_in_offset + self.fft_size <= self.input_buf.offset:
            # data_indexed is (end_index, length) for some reason
            yield self.input_buf.data_indexed(
                self.next_in_offset + self.fft_size, self.fft_size)
            self.next_in_offset += m.floor(self.fft_size * (1.0 - self.overlap))


    def _init_swipe(self):
        '''
        Initializes the log-spaced frequency grid (up to Nyquist) and the SWIPE
        kernels for frequencies up to the user selected max_freq.

        The default pitch resolution (cres) of 10 cents produces 120 pitch
        candidates per octave, which, after parabolic interpolation, is sufficient
        to generate very precise pitch estimates.

        '''
        
        numberOfLogSpacedFreqs = int(np.log2(self.sample_rate / (2 * self.min_freq)) * (1200 / self.cres))
        self.logSpacedFreqs = np.logspace(np.log2(self.min_freq), np.log2(self.sample_rate // 2), num=numberOfLogSpacedFreqs, base=2)

        # The pitch candidates for the kernels are a subset of the log-spaced freqs only up to the user's max_freq.
        fMaxIndex = np.searchsorted(self.logSpacedFreqs, self.max_freq)
        self.pitchCandidates = self.logSpacedFreqs[:fMaxIndex]
        
        self.kernels = np.zeros((len(self.pitchCandidates), len(self.logSpacedFreqs)))
        for i, freq in enumerate(self.pitchCandidates):
            self.kernels[i] = calcKernel(freq, self.logSpacedFreqs)


    def estimate_pitch(self, frame: np.ndarray) -> Optional[float]:
        spectrum = np.abs(np.fft.rfft(frame[0, :] * self.proc.window))

        # Generate the frequency bins (linear) to that correspond with the spectrum data
        freq_lin = np.arange(len(spectrum), dtype='float64')
        freq_lin *= float(self.sample_rate) / float(self.fft_size)

        # Create spline mapping from linear frequency to amplitude
        # Apply this spline to the log-spaced frequencies and normalize
        specLog = np.interp(self.logSpacedFreqs, freq_lin, spectrum)
        specLogRMS = np.sqrt(np.mean(specLog**2))
        specLogNorm = specLog / specLogRMS

        # Get the correlation between the audio frame and the kernels
        pitchStrengths = np.matmul(self.kernels, specLogNorm)
        
        # Get the highest strength index
        idxMax = np.argmax(pitchStrengths)

        # The highest values for pitchStrength (confidence) will come from voiced pitches
        # that nearly identially match the kernel for that pitch, with a peak of around 16.
        # Using a slightly lower value, such as the default of 10, is a good compromise
        # for most voices.

        # Use parabolic interp to get frequency values between resolution bins
        if 0 < idxMax < len(pitchStrengths) - 1:
            y1 = pitchStrengths[idxMax - 1]
            y2 = pitchStrengths[idxMax]
            y3 = pitchStrengths[idxMax + 1]
            idxShift, _ = fastParabolicInterp(y1, y2, y3)
        else:
            idxShift = 0

        # Create a mapping from indices to frequencies
        # Apply spline to idxMax with a slight index shift
        f0 = np.interp(idxMax + idxShift, np.arange(len(self.logSpacedFreqs)), self.logSpacedFreqs)

        # Check decibal value and confidence before output
        db = 10 * np.log10(specLog[idxMax] ** 2 / self.fft_size ** 2)

        if (db < self.min_db) or (pitchStrengths[idxMax] < self.conf):
            return np.nan
        else:
            return f0