# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'friture.ui'
#
# Created: Fri Oct  9 16:32:48 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 573)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PlotZoneImage = ImagePlot(self.centralwidget)
        self.PlotZoneImage.setObjectName("PlotZoneImage")
        self.gridLayout = QtGui.QGridLayout(self.PlotZoneImage)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3.addWidget(self.PlotZoneImage, 0, 0, 1, 6)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox_inputDevice = QtGui.QComboBox(self.centralwidget)
        self.comboBox_inputDevice.setObjectName("comboBox_inputDevice")
        self.gridLayout_3.addWidget(self.comboBox_inputDevice, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 2, 1, 1)
        self.comboBox_freqscale = QtGui.QComboBox(self.centralwidget)
        self.comboBox_freqscale.setObjectName("comboBox_freqscale")
        self.comboBox_freqscale.addItem(QtCore.QString())
        self.comboBox_freqscale.addItem(QtCore.QString())
        self.gridLayout_3.addWidget(self.comboBox_freqscale, 1, 3, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 4, 1, 1)
        self.comboBox_fftsize = QtGui.QComboBox(self.centralwidget)
        self.comboBox_fftsize.setObjectName("comboBox_fftsize")
        self.comboBox_fftsize.addItem(QtCore.QString())
        self.comboBox_fftsize.addItem(QtCore.QString())
        self.comboBox_fftsize.addItem(QtCore.QString())
        self.comboBox_fftsize.addItem(QtCore.QString())
        self.comboBox_fftsize.addItem(QtCore.QString())
        self.comboBox_fftsize.addItem(QtCore.QString())
        self.comboBox_fftsize.addItem(QtCore.QString())
        self.comboBox_fftsize.addItem(QtCore.QString())
        self.comboBox_fftsize.addItem(QtCore.QString())
        self.comboBox_fftsize.addItem(QtCore.QString())
        self.gridLayout_3.addWidget(self.comboBox_fftsize, 1, 5, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.spinBox_specmin = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_specmin.setKeyboardTracking(False)
        self.spinBox_specmin.setMinimum(-200)
        self.spinBox_specmin.setMaximum(200)
        self.spinBox_specmin.setProperty("value", QtCore.QVariant(-100))
        self.spinBox_specmin.setObjectName("spinBox_specmin")
        self.gridLayout_3.addWidget(self.spinBox_specmin, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 2, 1, 1)
        self.spinBox_specmax = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_specmax.setKeyboardTracking(False)
        self.spinBox_specmax.setMinimum(-200)
        self.spinBox_specmax.setMaximum(200)
        self.spinBox_specmax.setProperty("value", QtCore.QVariant(-20))
        self.spinBox_specmax.setObjectName("spinBox_specmax")
        self.gridLayout_3.addWidget(self.spinBox_specmax, 2, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 4, 1, 1)
        self.doubleSpinBox_timerange = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_timerange.setDecimals(1)
        self.doubleSpinBox_timerange.setMinimum(0.1)
        self.doubleSpinBox_timerange.setMaximum(1000.0)
        self.doubleSpinBox_timerange.setProperty("value", QtCore.QVariant(10.0))
        self.doubleSpinBox_timerange.setObjectName("doubleSpinBox_timerange")
        self.gridLayout_3.addWidget(self.doubleSpinBox_timerange, 2, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidgetLevels = QtGui.QDockWidget(MainWindow)
        self.dockWidgetLevels.setObjectName("dockWidgetLevels")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_rms = QtGui.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_rms.setFont(font)
        self.label_rms.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_rms.setObjectName("label_rms")
        self.gridLayout_4.addWidget(self.label_rms, 0, 0, 1, 1)
        self.meter = qsynthMeter(self.dockWidgetContents)
        self.meter.setObjectName("meter")
        self.gridLayout_4.addWidget(self.meter, 0, 1, 2, 1)
        self.label_peak = QtGui.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_peak.setFont(font)
        self.label_peak.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_peak.setObjectName("label_peak")
        self.gridLayout_4.addWidget(self.label_peak, 0, 2, 1, 1)
        self.label_rms_legend = QtGui.QLabel(self.dockWidgetContents)
        self.label_rms_legend.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_rms_legend.setObjectName("label_rms_legend")
        self.gridLayout_4.addWidget(self.label_rms_legend, 1, 0, 1, 1)
        self.label_peak_legend = QtGui.QLabel(self.dockWidgetContents)
        self.label_peak_legend.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_peak_legend.setObjectName("label_peak_legend")
        self.gridLayout_4.addWidget(self.label_peak_legend, 1, 2, 1, 1)
        self.dockWidgetLevels.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetLevels)
        self.dockWidgetStatistics = QtGui.QDockWidget(MainWindow)
        self.dockWidgetStatistics.setObjectName("dockWidgetStatistics")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LabelLevel = QtGui.QLabel(self.dockWidgetContents_2)
        self.LabelLevel.setObjectName("LabelLevel")
        self.gridLayout_2.addWidget(self.LabelLevel, 0, 0, 1, 1)
        self.dockWidgetStatistics.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetStatistics)
        self.dockWidgetScope = QtGui.QDockWidget(MainWindow)
        self.dockWidgetScope.setObjectName("dockWidgetScope")
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.PlotZoneUp = TimePlot(self.dockWidgetContents_4)
        self.PlotZoneUp.setObjectName("PlotZoneUp")
        self.gridLayout_5.addWidget(self.PlotZoneUp, 0, 0, 1, 1)
        self.dockWidgetScope.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetScope)
        self.dockWidgetSpectrum = QtGui.QDockWidget(MainWindow)
        self.dockWidgetSpectrum.setObjectName("dockWidgetSpectrum")
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.PlotZoneSpect = SpectPlot(self.dockWidgetContents_5)
        self.PlotZoneSpect.setObjectName("PlotZoneSpect")
        self.gridLayout_6.addWidget(self.PlotZoneSpect, 0, 0, 1, 1)
        self.dockWidgetSpectrum.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetSpectrum)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setCheckable(True)
        self.actionStart.setChecked(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/start.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/start.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/start.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.actionStart.setIcon(icon)
        self.actionStart.setObjectName("actionStart")
        self.toolBar.addAction(self.actionStart)

        self.retranslateUi(MainWindow)
        self.comboBox_fftsize.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Friture", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Sound input:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Frequency scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_freqscale.setItemText(0, QtGui.QApplication.translate("MainWindow", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_freqscale.setItemText(1, QtGui.QApplication.translate("MainWindow", "Logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "FFT Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fftsize.setItemText(0, QtGui.QApplication.translate("MainWindow", "32 points", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fftsize.setItemText(1, QtGui.QApplication.translate("MainWindow", "64 points", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fftsize.setItemText(2, QtGui.QApplication.translate("MainWindow", "128 points", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fftsize.setItemText(3, QtGui.QApplication.translate("MainWindow", "256 points", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fftsize.setItemText(4, QtGui.QApplication.translate("MainWindow", "512 points", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fftsize.setItemText(5, QtGui.QApplication.translate("MainWindow", "1024 points", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fftsize.setItemText(6, QtGui.QApplication.translate("MainWindow", "2048 points", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fftsize.setItemText(7, QtGui.QApplication.translate("MainWindow", "4096 points", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fftsize.setItemText(8, QtGui.QApplication.translate("MainWindow", "8192 points", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fftsize.setItemText(9, QtGui.QApplication.translate("MainWindow", "16384 points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Min color", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_specmin.setSuffix(QtGui.QApplication.translate("MainWindow", " dB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Max color", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_specmax.setSuffix(QtGui.QApplication.translate("MainWindow", " dB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Time range", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_timerange.setSuffix(QtGui.QApplication.translate("MainWindow", " s", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetLevels.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Input levels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rms.setText(QtGui.QApplication.translate("MainWindow", "-100.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_peak.setText(QtGui.QApplication.translate("MainWindow", "-100.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rms_legend.setText(QtGui.QApplication.translate("MainWindow", "dBFS\n"
"RMS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_peak_legend.setText(QtGui.QApplication.translate("MainWindow", "dBFS\n"
"peak", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetStatistics.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelLevel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetScope.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Scope", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetSpectrum.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart.setToolTip(QtGui.QApplication.translate("MainWindow", "Start/Stop", None, QtGui.QApplication.UnicodeUTF8))

from timeplot import TimePlot
from qsynthmeter import qsynthMeter
from imageplot import ImagePlot
from spectplot import SpectPlot
import resource_rc
