#!/usr/bin/env python3
import sys

# allow this script to be executed as a child of another script (lsprofcalltree, for example)
# (add at the end to favor system-installed packages)
sys.path.append('.')

from friture.analyzer import main

main()
